##########  说明  ##########

#配置文件格式的注意事项：
#   配置项的缩进关系不可更改
#   配置项冒号后面需要有空格

##########  基本配置  ##########

workflow:
  # Workflow系统数据库相关配置
  datasource:
    #   数据库类型，目前支持oracle
    type: oracle
    #   数据库url配置
    #    oracle：jdbc:oracle:thin:@//localhost:1521/orcl
    url: jdbc:oracle:thin:@//localhost:1521/orcl
    username: workflow
    password: root
      #   连接池配置，如有要求自行修改
    minimum-idle: 10
    maximum-pool-size: 100
  #服务器端口配置
  port: 8089

