Configuration:
  status: warn

  Properties:
    Property:
    - name: log.path
      value: logs
    - name: project.name
      value: aims

  Appenders:
    Console:
      name: CONSOLE
      target: SYSTEM_OUT
      PatternLayout:
        pattern: "%d{HH:mm:ss,SSS}:%4p %t (%F:%L) - %m%n"
    RollingFile:
      name: ROLLING_FILE
      ignoreExceptions: false
      fileName: ${log.path}/${project.name}.log
      filePattern: "${log.path}/$${date:yyyy-MM}/${project.name}-%d{yyyy-MM-dd}-%i.log.gz"
      PatternLayout:
        pattern: "%d{yyyy-MM-dd HH:mm:ss,SSS}:%4p %t (%F:%L) - %m%n"
      Policies:
        SizeBasedTriggeringPolicy:
           size: "10 MB"
      DefaultRolloverStrategy:
         max: 1000

  Loggers:
    Root:
      level: INFO
      AppenderRef:
        - ref: CONSOLE
        - ref: ROLLING_FILE